### ISSUE TITLE
Virtual Tutorial To-Do List - Part 1

### ISSUE THREAD

**Issue by jukent** [NCAR/ncar-python-tutorial#116]
- [x] Identify all of parts, create an outline

- [x] Branch/PR just for part 1 
         - pair programming review w @kmpaul 
         - get xdev team to read/add missing content/create PR
         - repeat

- [x] Create Nikola md page for part 1

- [x] Reach out to Beta testers of part 1

- [ ] Post and Announcement

Repeat for part 2

References:

-  #105  -- for 0 to 30 tutorial content discussion

-  #99  -- for overall tutorial curricula discussion
